In [10]:
import joblib
import pandas as pd

### Loading the rain prediction model

In [11]:
aussie_rain2 = joblib.load('..\\model\\aussie_rain.joblib')

Dictionary with all required objects from predict_next_day_rain.ipynb that are needed to make predictions on any input data

aussie_rain = {  
  'model': model,  
  'imputer': imputer,  
  'scaler': scaler,  
  'encoder': encoder,  
  'input_cols': input_cols,  
  'target_col': target_col,  
  'numeric_cols': numeric_cols,  
  'categorical_cols': categorical_cols,  
  'encoded_cols': encoded_cols  
}  

After loading the model, you can call any of the objects in the dictionary to perform a specific operation

In [12]:
aussie_rain2['model'].coef_

array([[ 8.98631313e-01, -2.87991534e+00,  3.16277797e+00,
         8.54245853e-01, -1.67139390e+00,  6.76440065e+00,
        -9.42321897e-01, -1.42842863e+00,  3.22892517e-01,
         5.99531536e+00,  5.46385628e+00, -9.17680428e+00,
        -1.62297095e-01,  1.28765974e+00,  4.74715135e-01,
         2.02143027e+00,  6.01650198e-01, -5.52482047e-01,
         4.78142790e-01,  7.66971934e-03,  3.46814543e-01,
        -3.52277229e-01,  1.79710726e-01,  4.40486437e-01,
        -1.39817863e-02,  2.89438264e-02,  2.58147356e-01,
        -2.12055746e-02, -4.27949262e-02, -4.83141694e-01,
        -1.37563362e-01, -5.76059630e-01, -7.87523487e-01,
        -2.55404066e-01, -3.28883934e-01, -5.69004401e-01,
         8.18300210e-02,  1.33825047e-02,  6.41275025e-02,
        -9.02054551e-01, -4.44329881e-01,  8.51713158e-03,
        -4.60612384e-01, -4.65518114e-01, -6.94989159e-02,
         1.91158759e-01,  4.50475879e-01,  6.08121047e-01,
         4.27313870e-01, -2.83312576e-02,  2.51546743e-01,
        -3.21605627e-01,  4.24955974e-01, -5.90373050e-02,
        -1.13200231e-01, -7.28376994e-01,  3.66452627e-01,
         1.83590394e-01,  1.83975134e-01,  1.86604089e-01,
        -2.49269517e-01,  1.79482292e-02,  7.03402835e-01,
        -8.00021386e-01, -1.92344128e-01, -1.61797858e-01,
        -1.58986115e-01, -6.31002993e-02, -2.23550789e-01,
        -2.32392756e-01, -3.21152869e-01, -1.65569069e-01,
        -1.58848988e-01, -1.10976069e-01, -3.25274371e-02,
        -5.06276795e-02, -9.41989606e-02, -9.08174608e-02,
        -2.23155636e-01, -2.58528271e-01, -2.00815532e-01,
         9.74916981e-02, -3.18773749e-01, -2.93565850e-02,
        -3.28613663e-01,  2.98652067e-02, -2.10664280e-02,
         1.44052912e-01, -6.17689281e-02, -5.69744432e-02,
        -4.08535653e-01, -3.08123486e-01, -4.05435093e-01,
        -1.94829238e-01, -6.02913911e-02, -8.69207449e-02,
        -5.71123227e-02, -1.61295510e-02, -2.69540934e-01,
        -2.39853698e-01, -1.52500746e-01, -2.34834210e-01,
         3.81965523e-02, -3.11413149e-01, -8.02450066e-02,
         2.84545548e-01,  2.21850844e-01, -2.65448890e-01,
        -2.41174193e-01, -3.66880733e-01, -3.16862699e-01,
        -3.70021670e-01, -1.80370428e-01, -3.34990520e-02,
        -2.75975563e-01,  7.49330026e-02, -1.47351671e+00,
        -9.76037377e-01]])

### Model prediction using test set

Load the processed test set - Clean data

In [22]:
test_inputs_df = pd.read_parquet('..\\data\\processed\\test_inputs.parquet')
test_inputs_df.head()

,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,...,WindDir3pm_SE,WindDir3pm_SSE,WindDir3pm_SSW,WindDir3pm_SW,WindDir3pm_W,WindDir3pm_WNW,WindDir3pm_WSW,WindDir3pm_nan,RainToday_No,RainToday_Yes
2498,Albury,0.681604,0.801512,0.000000,0.037741,0.526244,ENE,0.372093,NaN,ESE,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2499,Albury,0.693396,0.725898,0.001078,0.037741,0.526244,SSE,0.341085,SSE,SE,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2500,Albury,0.634434,0.527410,0.005930,0.037741,0.526244,ENE,0.325581,ESE,ENE,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2501,Albury,0.608491,0.538752,0.042049,0.037741,0.526244,SSE,0.255814,SE,SSE,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2502,Albury,0.566038,0.523629,0.018329,0.037741,0.526244,ENE,0.193798,SE,SSE,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [23]:
numeric_cols = aussie_rain2['numeric_cols']
encoded_cols = aussie_rain2['encoded_cols']

In [25]:
X_test = test_inputs_df[numeric_cols + encoded_cols]

Make predictions using the test set

In [ ]:
test_pred = aussie_rain2['model'].predict(X_test)
test_pred

array(['No', 'No', 'Yes', ..., 'No', 'No', 'No'],
      shape=(25710,), dtype=object)

### Evaluate model performance on test set

In [18]:
from sklearn.metrics import accuracy_score

In [19]:
test_target = pd.read_parquet('..\\data\\processed\\test_target.parquet')
test_target['RainTomorrow']

2498       No
2499      Yes
2500      Yes
2501      Yes
2502       No
         ...
145454     No
145455     No
145456     No
145457     No
145458     No
Name: RainTomorrow, Length: 25710, dtype: str

In [20]:
X_test

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,...,WindDir3pm_SE,WindDir3pm_SSE,WindDir3pm_SSW,WindDir3pm_SW,WindDir3pm_W,WindDir3pm_WNW,WindDir3pm_WSW,WindDir3pm_nan,RainToday_No,RainToday_Yes
2498,0.681604,0.801512,0.000000,0.037741,0.526244,0.372093,0.000000,0.080460,0.46,0.17,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2499,0.693396,0.725898,0.001078,0.037741,0.526244,0.341085,0.069231,0.195402,0.54,0.30,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2500,0.634434,0.527410,0.005930,0.037741,0.526244,0.325581,0.084615,0.448276,0.62,0.67,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2501,0.608491,0.538752,0.042049,0.037741,0.526244,0.255814,0.069231,0.195402,0.74,0.65,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2502,0.566038,0.523629,0.018329,0.037741,0.526244,0.193798,0.046154,0.103448,0.92,0.63,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145454,0.283019,0.502836,0.000000,0.037741,0.526244,0.193798,0.115385,0.149425,0.59,0.27,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
145455,0.266509,0.533081,0.000000,0.037741,0.526244,0.193798,0.100000,0.126437,0.51,0.24,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
145456,0.285377,0.568998,0.000000,0.037741,0.526244,0.124031,0.100000,0.103448,0.56,0.21,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
145457,0.327830,0.599244,0.000000,0.037741,0.526244,0.240310,0.069231,0.103448,0.53,0.24,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
145458,0.384434,0.601134,0.000000,0.037741,0.526244,0.170543,0.100000,0.080460,0.51,0.24,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

Calculate the accuracy score

In [ ]:
accuracy_score(test_target, test_pred)

0.8420070011668611